name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - run: go get -u -v github.com/golang/dep/cmd/dep
    - run: ${HOME}/go/bin/dep ensure -v -verndor-only
    - run: go test -v ./...

      
