name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | INSTALL_DIRECTORY="${GOROOT}/bin" sh
    - run: dep ensure -v -vendor-only
    - run: go test -v ./...

      
