name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup go env
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.8
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run go get
        run: |
          go get -v
      - name: Run test
        run: |
          go test -v ./...
