name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go env
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.8
      env:
        GOPATH: "${HOME}/go"
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: "${HOME}/go/src/github.com/dragon3/go-simple-http-proxy"
    - name: Install dep
      run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | INSTALL_DIRECTORY="${GOROOT}/bin" sh
    - name: Run dep ensure
      run: dep ensure -v -vendor-only
    - name: Run test
      run: go test -v ./...

      
